# Generated by Django 2.1.15 on 2020-05-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_info',
            fields=[
                ('ISBN', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(max_length=200, verbose_name='author')),
                ('publisher', models.CharField(max_length=200, verbose_name='publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=1000, verbose_name='password')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('gender', models.CharField(max_length=7, verbose_name='gender')),
                ('age', models.IntegerField(verbose_name='age')),
            ],
        ),
    ]
