# Generated by Django 2.1.15 on 2020-05-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('NO', models.IntegerField(max_length=100, primary_key=True, serialize=False, verbose_name='NO')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='credit')),
            ],
        ),
    ]
