# Generated by Django 2.1.15 on 2020-05-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('ISBN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookmanageapp.Book_info')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='NO',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='NO'),
        ),
    ]
