# Generated by Django 2.1.15 on 2020-05-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='ISBN',
        ),
        migrations.DeleteModel(
            name='Book_info',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
