# Generated by Django 2.1.15 on 2020-05-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0006_account_book_info_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('NO', models.IntegerField(primary_key=True, serialize=False, verbose_name='NO')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='cost')),
                ('date', models.CharField(max_length=11, verbose_name='date')),
                ('number', models.IntegerField(verbose_name='number')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('NO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookmanageapp.Book_info')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('stock', models.IntegerField(verbose_name='stock')),
            ],
        ),
        migrations.AlterField(
            model_name='book_info',
            name='ISBN',
            field=models.CharField(max_length=50, unique=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='order',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanageapp.Book_info', to_field='ISBN'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanageapp.Userinfo', to_field='username'),
        ),
    ]
