# Generated by Django 2.1.15 on 2020-05-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0007_auto_20200510_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ISBN',
        ),
        migrations.AddField(
            model_name='order',
            name='Book_NO',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookmanageapp.Book_info'),
            preserve_default=False,
        ),
    ]
