# Generated by Django 2.1.15 on 2020-05-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0008_auto_20200511_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
