# Generated by Django 2.1.15 on 2020-05-11 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanageapp', '0010_auto_20200511_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('NO', models.IntegerField(primary_key=True, serialize=False, verbose_name='NO')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('date', models.CharField(max_length=11, verbose_name='date')),
                ('number', models.IntegerField(verbose_name='number')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('Book_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanageapp.Book_info')),
                ('user_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmanageapp.Userinfo')),
            ],
        ),
    ]
